#!/usr/bin/env python3
"""
Patch Script - Environment Variable Setup for update.py
Creates .env file and updates update.py to use environment variables
"""

import os
import re
import sys
from pathlib import Path

# ============================================================
# COLORS FOR OUTPUT
# ============================================================

class Colors:
    GREEN = '\033[92m'
    YELLOW = '\033[93m'
    RED = '\033[91m'
    CYAN = '\033[96m'
    MAGENTA = '\033[95m'
    RESET = '\033[0m'
    BOLD = '\033[1m'

def print_color(text, color=Colors.RESET):
    print(f"{color}{text}{Colors.RESET}")

# ============================================================
# CONFIGURATION
# ============================================================

# The hardcoded token to replace (GITHUB_TOKEN from update.py)
HARDCODED_TOKEN = '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'

# Files to patch (only update.py)
FILES_TO_PATCH = ['update.py']

# .env file content template
ENV_TEMPLATE = """# DSTerminal Environment Variables
# Generated by patch script on {date}

# GitHub Token (required for update checks)
GITHUB_TOKEN={token}

# VirusTotal API Key (for threat intelligence)
VT_API_KEY=957166d424812a397e328022b84594a8c02757814f6c04518dce7e81179b4b79

# Current version
CURRENT_VERSION=3.1.113

# Optional: Set your operator name and session ID
# SOC_OPERATOR_NAME=OP-USERNAME
# SOC_SESSION_ID=SESSION-ID
"""

# ============================================================
# MAIN PATCH FUNCTIONS
# ============================================================

def create_env_file(token, workspace_dir=None):
    """Create .env file with token and other variables"""
    if workspace_dir is None:
        workspace_dir = Path.cwd()
    
    env_path = workspace_dir / '.env'
    
    # Check if .env already exists
    if env_path.exists():
        print_color(f"⚠️  .env file already exists at: {env_path}", Colors.YELLOW)
        response = input(f"{Colors.YELLOW}Overwrite? (y/N): {Colors.RESET}").strip().lower()
        if response != 'y':
            print_color("Keeping existing .env file", Colors.GREEN)
            return env_path
    
    # Create .env content
    from datetime import datetime
    env_content = ENV_TEMPLATE.format(
        date=datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
        token=token
    )
    
    # Write .env file
    try:
        with open(env_path, 'w') as f:
            f.write(env_content)
        print_color(f"✅ .env file created at: {env_path}", Colors.GREEN)
        return env_path
    except Exception as e:
        print_color(f"❌ Failed to create .env file: {e}", Colors.RED)
        return None

def patch_update_py(file_path, token_to_replace, env_var_name='GITHUB_TOKEN'):
    """Patch update.py to use environment variable instead of hardcoded token"""
    
    if not os.path.exists(file_path):
        print_color(f"❌ File not found: {file_path}", Colors.RED)
        return False
    
    # Read the file
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    original_content = content
    changes_made = False
    
    # Pattern 1: Replace hardcoded token with environment variable
    # Search for: self.github_token = self.config.get("GITHUB_TOKEN", "ghp_...")
    pattern1 = r'self\.github_token = self\.config\.get\("GITHUB_TOKEN",\s*"[^"]*"\)'
    replacement1 = 'self.github_token = os.environ.get("GITHUB_TOKEN", self.config.get("GITHUB_TOKEN", ""))'
    
    if re.search(pattern1, content):
        content = re.sub(pattern1, replacement1, content)
        changes_made = True
        print_color("  ✓ Replaced hardcoded token with environment variable", Colors.GREEN)
    else:
        print_color("  ⚠️ Pattern 1 not found - token may already be using environment variable", Colors.YELLOW)
    
    # Pattern 2: Replace the specific token string directly (if present)
    if token_to_replace in content:
        # Count occurrences
        count = content.count(token_to_replace)
        content = content.replace(token_to_replace, f'os.environ.get("{env_var_name}", "")')
        if count > 0:
            changes_made = True
            print_color(f"  ✓ Replaced {count} occurrence(s) of hardcoded token", Colors.GREEN)
    
    # Pattern 3: Ensure os is imported (if not already)
    if 'import os' not in content and 'from os import' not in content:
        # Find the first import line
        import_lines = re.findall(r'^import .*$', content, re.MULTILINE)
        if import_lines:
            # Insert after the last import
            last_import = import_lines[-1]
            content = content.replace(last_import, f"{last_import}\nimport os")
            changes_made = True
            print_color("  ✓ Added os import", Colors.GREEN)
    
    # If no changes were made, check if the file already uses environment variables
    if not changes_made:
        if 'os.environ.get' in content and 'GITHUB_TOKEN' in content:
            print_color("  ✓ File already uses environment variables", Colors.GREEN)
            return True
        else:
            print_color("  ⚠️ No changes made - file may need manual update", Colors.YELLOW)
            return False
    
    # Create backup before writing
    backup_path = f"{file_path}.backup"
    try:
        with open(backup_path, 'w', encoding='utf-8') as f:
            f.write(original_content)
        print_color(f"  ✓ Backup created: {backup_path}", Colors.CYAN)
    except Exception as e:
        print_color(f"  ⚠️ Could not create backup: {e}", Colors.YELLOW)
    
    # Write the patched content
    try:
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(content)
        print_color(f"  ✅ Successfully patched: {file_path}", Colors.GREEN)
        return True
    except Exception as e:
        print_color(f"  ❌ Failed to write patch: {e}", Colors.RED)
        # Restore backup
        try:
            with open(backup_path, 'r', encoding='utf-8') as f:
                content = f.read()
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(content)
            print_color(f"  ✓ Restored from backup", Colors.GREEN)
        except:
            pass
        return False

def create_dotenv_import(file_path):
    """Add python-dotenv import to update.py if not present"""
    
    if not os.path.exists(file_path):
        return False
    
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Check if dotenv is already imported
    if 'from dotenv import load_dotenv' in content or 'import dotenv' in content:
        print_color("  ✓ python-dotenv already imported", Colors.GREEN)
        return True
    
    # Find the first import line
    import_lines = re.findall(r'^import .*$', content, re.MULTILINE)
    from_imports = re.findall(r'^from .* import .*$', content, re.MULTILINE)
    
    # Insert dotenv import after other imports
    if import_lines or from_imports:
        last_import = import_lines[-1] if import_lines else from_imports[-1]
        
        # Insert after the last import
        dotenv_import = "try:\n    from dotenv import load_dotenv\n    load_dotenv()\nexcept ImportError:\n    pass\n"
        content = content.replace(last_import, f"{last_import}\n\n{dotenv_import}")
        
        # Write the file
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(content)
        
        print_color("  ✓ Added python-dotenv import", Colors.GREEN)
        return True
    
    return False

# ============================================================
# VERIFICATION FUNCTION
# ============================================================

def verify_patch(file_path):
    """Verify that the patch was applied successfully"""
    
    if not os.path.exists(file_path):
        return False
    
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Check if hardcoded token is gone
    if HARDCODED_TOKEN in content:
        print_color(f"  ❌ Hardcoded token still found in {file_path}", Colors.RED)
        return False
    
    # Check if environment variable is used
    if 'os.environ.get' in content and 'GITHUB_TOKEN' in content:
        print_color(f"  ✅ {file_path} is using environment variables", Colors.GREEN)
        return True
    else:
        print_color(f"  ⚠️ {file_path} may not be using environment variables correctly", Colors.YELLOW)
        return False

# ============================================================
# MAIN FUNCTION
# ============================================================

def main():
    """Main patch execution"""
    
    print_color("=" * 60, Colors.CYAN)
    print_color("🔧 DSTERMINAL PATCH - ENVIRONMENT VARIABLE SETUP", Colors.MAGENTA + Colors.BOLD)
    print_color("=" * 60, Colors.CYAN)
    
    # Get the current directory
    current_dir = Path.cwd()
    print_color(f"\n📁 Working directory: {current_dir}", Colors.CYAN)
    
    # Step 1: Create .env file
    print_color("\n📝 Step 1: Creating .env file...", Colors.YELLOW)
    
    # Ask for new token or use existing
    print_color(f"\nCurrent hardcoded token: {HARDCODED_TOKEN[:10]}...{HARDCODED_TOKEN[-10:]}", Colors.CYAN)
    use_new_token = input(f"{Colors.YELLOW}Use a new token instead of the hardcoded one? (y/N): {Colors.RESET}").strip().lower()
    
    if use_new_token == 'y':
        new_token = input(f"{Colors.CYAN}Enter new GitHub token: {Colors.RESET}").strip()
        if not new_token:
            print_color("⚠️  No token entered, using existing token", Colors.YELLOW)
            new_token = HARDCODED_TOKEN
    else:
        new_token = HARDCODED_TOKEN
    
    env_file = create_env_file(new_token, current_dir)
    if not env_file:
        print_color("❌ Failed to create .env file. Exiting.", Colors.RED)
        return
    
    # Step 2: Patch update.py only
    print_color("\n📝 Step 2: Patching update.py...", Colors.YELLOW)
    
    for file_path in FILES_TO_PATCH:
        full_path = current_dir / file_path
        
        if not full_path.exists():
            print_color(f"❌ File not found: {file_path}", Colors.RED)
            continue
        
        print_color(f"\n🔧 Processing: {file_path}", Colors.CYAN)
        
        # Create backup
        backup_path = full_path.parent / f"{full_path.name}.backup"
        try:
            with open(full_path, 'r', encoding='utf-8') as f:
                backup_content = f.read()
            with open(backup_path, 'w', encoding='utf-8') as f:
                f.write(backup_content)
        except:
            pass
        
        # Patch the file
        success = patch_update_py(full_path, HARDCODED_TOKEN)
        
        if success:
            # Add dotenv import
            create_dotenv_import(full_path)
            
            # Verify the patch
            verify_patch(full_path)
    
    # Step 3: Create .gitignore if it doesn't exist
    print_color("\n📝 Step 3: Updating .gitignore...", Colors.YELLOW)
    
    gitignore_path = current_dir / '.gitignore'
    env_pattern = '.env'
    
    if gitignore_path.exists():
        with open(gitignore_path, 'r') as f:
            gitignore_content = f.read()
        
        if env_pattern not in gitignore_content:
            with open(gitignore_path, 'a') as f:
                f.write(f"\n# Environment variables\n.env\n*.env\n*.key\n*.secret\n")
            print_color("  ✓ Added .env to .gitignore", Colors.GREEN)
        else:
            print_color("  ✓ .env already in .gitignore", Colors.GREEN)
    else:
        with open(gitignore_path, 'w') as f:
            f.write(f"# Environment variables\n.env\n*.env\n*.key\n*.secret\n\n# Python\n__pycache__/\n*.pyc\n*.pyo\n*.pyd\nvenv/\nenv/\n")
        print_color("  ✓ Created .gitignore with .env pattern", Colors.GREEN)
    
    # Step 4: Add instructions
    print_color("\n" + "=" * 60, Colors.CYAN)
    print_color("✅ PATCH COMPLETED SUCCESSFULLY!", Colors.GREEN + Colors.BOLD)
    print_color("=" * 60, Colors.CYAN)
    
    print_color("\n📋 What was done:", Colors.MAGENTA)
    print_color("  1. Created .env file with your GitHub token", Colors.GREEN)
    print_color("  2. Patched update.py to use environment variables", Colors.GREEN)
    print_color("  3. Added python-dotenv import to update.py", Colors.GREEN)
    print_color("  4. Updated .gitignore to exclude .env files", Colors.GREEN)
    
    print_color("\n🔑 Next steps:", Colors.MAGENTA)
    print_color(f"  1. Review the changes in update.py", Colors.CYAN)
    print_color(f"  2. Test the update functionality", Colors.CYAN)
    print_color(f"  3. Commit the changes:", Colors.CYAN)
    print_color(f"     git add update.py .gitignore .env", Colors.YELLOW)
    print_color(f"     git commit -m \"Use environment variables for GitHub token\"", Colors.YELLOW)
    print_color(f"     git push --set-upstream origin test-update-feature", Colors.YELLOW)
    
    print_color(f"\n⚠️  IMPORTANT: Never commit the .env file!", Colors.RED + Colors.BOLD)
    print_color(f"   The .env file contains secrets and should stay local only.", Colors.RED)
    
    print_color(f"\n📌 To use the new environment variable:", Colors.MAGENTA)
    print_color(f"   In your code, use: os.environ.get('GITHUB_TOKEN', '')", Colors.CYAN)
    print_color(f"   Or with dotenv: load_dotenv() then os.environ.get('GITHUB_TOKEN')", Colors.CYAN)
    
    print_color("\n🎉 Patch complete! Your update.py is now using environment variables.", Colors.GREEN)

# ============================================================
# RUN THE PATCH
# ============================================================

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print_color("\n\n⚠️  Patch cancelled by user", Colors.YELLOW)
        sys.exit(1)
    except Exception as e:
        print_color(f"\n❌ Unexpected error: {e}", Colors.RED)
        import traceback
        traceback.print_exc()
        sys.exit(1)